### ISSUE TITLE
Output is not archivable because folder output is not created 

### ISSUE THREAD

**Issue by pietroastolfi** [dipy/bl_apps_dipy_fit_csd#1]
Hi,

I ran the app on BL and I obtained the following error after the execution of the script was successfull:
<img width="1142" alt="Schermata 2020-08-10 alle 15 28 18" src="https://user-images.githubusercontent.com/15109253/89788180-0e621700-db1f-11ea-9a4f-d9d8b4b8b8cd.png">

As stated by the error, you are not creating the output directory, which is critical for brainlife in order to find the created files.

**Comment by soichih** [comment]
@guaje is updating those dipy apps, I believe this App is on his TODO list.

**Comment by skoudoro** [comment]
ok, I just updated it on this commit bd49ba5bd7bda5967959484b5f70399b9f86b39e.

it should be fixed but let me try quickly

**Comment by skoudoro** [comment]
As you can see [here](https://brainlife.io/project/5b23e74316fe38002748e679/process/5f318f73a5b64357a7a4d2d3) it seems to be ok now.

The others app will be updated too.

Feel free to reopen the issue if more data should be copied in output.

Thank you for the feedback @pietroastolfi. Closing
